### ISSUE TITLE
Ошибка на старте

### ISSUE THREAD

**Issue by ffdown** [Em1tSan/NeuroGPT#15]
Opening NeuroGPT...
. : Не удается загрузить файл E:\son\Documents\WindowsPowerShell\profile.ps1. Файл
E:\son\Documents\WindowsPowerShell\profile.ps1 не имеет цифровой подписи. Невозможно выполнить сценарий в указанной
системе. Для получения дополнительных сведений о выполнении сценариев и настройке политики выполнения см.
about_Execution_Policies по адресу https:/go.microsoft.com/fwlink/?LinkID=135170.
строка:1 знак:3
+ . 'E:\son\Documents\WindowsPowerShell\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Ошибка безопасности: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
Traceback (most recent call last):
  File "E:\AI\NeuroGPT-Portable\webui.py", line 25, in <module>
    import g4f
  File "E:\AI\NeuroGPT-Portable\g4f\__init__.py", line 3, in <module>
    from g4f.models import Model, ModelUtils
  File "E:\AI\NeuroGPT-Portable\g4f\models.py", line 6, in <module>
    class Model:
  File "E:\AI\NeuroGPT-Portable\g4f\models.py", line 12, in Model
    class gpt_35_turbo:
  File "E:\AI\NeuroGPT-Portable\g4f\models.py", line 38, in gpt_35_turbo
    best_provider: Provider.Provider = random.choice([getattr(Provider, active_provider) for active_provider in active_providers])
  File "E:\AI\NeuroGPT-Portable\g4f\models.py", line 38, in <listcomp>
    best_provider: Provider.Provider = random.choice([getattr(Provider, active_provider) for active_provider in active_providers])
AttributeError: module 'g4f.Provider' has no attribute 'Qidinam'

**Comment by ffdown** [comment]
вылечилось update_portable.bat =)
