### ISSUE TITLE
No module named ru_core_news_sm

### ISSUE THREAD

**Issue by vkamelin** [Em1tSan/NeuroGPT#49]
`python3.10 webui_ru.py`

```
Traceback (most recent call last):
  File "/home/gadjet/NeuroGPT/webui_ru.py", line 14, in <module>
    from backend.backend import app
  File "/home/gadjet/NeuroGPT/backend/backend.py", line 15, in <module>
    from .embedding_processing import embedding_processing
  File "/home/gadjet/NeuroGPT/backend/embedding_processing.py", line 9, in <module>
    import ru_core_news_sm
ModuleNotFoundError: No module named 'ru_core_news_sm'
```

**Comment by schametlich** [comment]
Мне помогло `python -m spacy download ru_core_news_sm`

**Comment by YuriyDY** [comment]
python3.10 -m spacy download ru_core_news_sm

**Comment by Em1tSan** [comment]
Исправлено в версии 1.5.4
