### ISSUE TITLE
Не найден модуль

### ISSUE THREAD

**Issue by Bismark-4** [Em1tSan/NeuroGPT#56]
Ошибка при запуске 'start.bat':
```
Completed.
Running NeuroGPT...
Traceback (most recent call `last):`
  File "E:\NeuroGPT\webui_ru.py", line 6, in <module>
    from modules import config
  File "E:\NeuroGPT\modules\config.py", line 6, in <module>
    import commentjson as json
ModuleNotFoundError: No module named 'commentjson'
Для продолжения нажмите любую клавишу . . .
```
При запуске 'start_endpoint.bat':
```
Completed.
Running NeuroGPT...
Traceback (most recent call last):
  File "E:\NeuroGPT\endpoint.py", line 3, in <module>
    from backend.backend import app
  File "E:\NeuroGPT\backend\backend.py", line 15, in <module>
    from .embedding_processing import embedding_processing
  File "E:\NeuroGPT\backend\embedding_processing.py", line 4, in <module>
    from zhconv import convert
ModuleNotFoundError: No module named 'zhconv'
Для продолжения нажмите любую клавишу . . .
```

**Comment by princeBel** [comment]
Такая же ошибка.
 pip install commentjson не помогло

**Comment by DobryninIlya** [comment]
второй раз батник попробуй запустить

**Comment by Nursultan911** [comment]
Не помогает

**Comment by Nursultan911** [comment]
попробуйте виртуальное окружение установить мне помогло

**Comment by Em1tSan** [comment]
Проблема исправлена в версии 1.5.4
